version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: stokkita-backend
    ports:
      - "3000:3000"
    env_file:
      - ./be/.env
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  worker:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: stokkita-worker
    command: ["node", "dist/api/worker.js"]
    env_file:
      - ./be/.env
    depends_on:
      - redis
      - rabbitmq
      - backend
    restart: unless-stopped
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: stokkita-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stokkita-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build:
      context: ./fe/cdp-project
      dockerfile: Dockerfile
    container_name: stokkita-frontend
    ports:
      - "5173:80" 
    depends_on:
      - backend
    restart: unless-stopped
